# General
title: OpenE2140
tagline: A modernized remake of Earth 2140
name: OpenE2140
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  OpenE2140 is a modernized remake of Earth 2140 with new features.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: bulma-clean-theme

plugins:
  - jekyll-feed

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: false

# Bulma Clean Theme
gh_sponsor: false
cookie_policy: false
force_theme: dark
fixed_navbar: top

# Exclude from processing.
exclude:
  - scripts/
  - misc/
  - docker/
  - .dockerignore
  - .gitignore
  - .editorconfig
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
